# Generated by Django 5.0.7 on 2024-07-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите заголовок",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "ad_id",
                    models.PositiveIntegerField(
                        help_text="Укажите ID обьявления",
                        unique=True,
                        verbose_name="ID обьявления",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="Укажите автора обьявления",
                        max_length=100,
                        verbose_name="Автор обьявления",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="Колличество просмотров"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Укажите позицию, на которой стоит обьявление",
                        verbose_name="Позиция обьявления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обьявление",
                "verbose_name_plural": "Обьявления",
            },
        ),
    ]
